import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AsciiProvider from "./AsciiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AsciiProvider>
                    <div className="w-screen max-w-screen h-screen max-h-screen overflow-hidden">{children}</div>
                </AsciiProvider>
            </body>
        </html>
    );
}
